In [1]:
import pandas as pd

In [2]:
# Read the CSV file
classdf = pd.read_csv('../data/train/virus_taxonomy.csv', sep=',')
classdf.rename(columns={'VirusGENBANKaccession':'contigId'}, inplace=True)
classdf

,contigId,Virus GENBANK accession,Virus name(s),Host source,Realm,Subrealm,Kingdom,Subkingdom,Phylum,Subphylum,Class,Subclass,Order,Suborder,Family,Subfamily,Genus,Subgenus,Species
0,MH447526,MH447526,Sulfolobus filamentous virus 1,archaea,Adnaviria,NaN,Zilligvirae,NaN,Taleaviricota,NaN,Tokiviricetes,NaN,Ligamenvirales,NaN,Lipothrixviridae,NaN,Alphalipothrixvirus,NaN,Alphalipothrixvirus beppuense
1,MK064563,MK064563,Sulfolobales Beppu filamentous virus 2,archaea,Adnaviria,NaN,Zilligvirae,NaN,Taleaviricota,NaN,Tokiviricetes,NaN,Ligamenvirales,NaN,Lipothrixviridae,NaN,Alphalipothrixvirus,NaN,Alphalipothrixvirus umijigokuense
2,AM087120,AM087120,Acidianus filamentous virus 3,archaea,Adnaviria,NaN,Zilligvirae,NaN,Taleaviricota,NaN,Tokiviricetes,NaN,Ligamenvirales,NaN,Lipothrixviridae,NaN,Betalipothrixvirus,NaN,Betalipothrixvirus acidiani
3,AF440571,AF440571,Sulfolobus islandicus filamentous virus,archaea,Adnaviria,NaN,Zilligvirae,NaN,Taleaviricota,NaN,Tokiviricetes,NaN,Ligamenvirales,NaN,Lipothrixviridae,NaN,Betalipothrixvirus,NaN,Betalipothrixvirus hveragerdiense
4,AM087122,AM087122,Acidianus filamentous virus 7,archaea,Adnaviria,NaN,Zilligvirae,NaN,Taleaviricota,NaN,Tokiviricetes,NaN,Ligamenvirales,NaN,Lipothrixviridae,NaN,Betalipothrixvirus,NaN,Betalipothrixvirus pezzuloense
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16226,JN819498,JN819498,Sida golden yellow vein deltasatellite 3,plants,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tolecusatellitidae,NaN,Deltasatellite,NaN,Deltasatellite sidaflavustertii
16227,U74627,U74627,tomato leaf curl deltasatellite,plants,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tolecusatellitidae,NaN,Deltasatellite,NaN,Deltasatellite solani
16228,JN819495,JN819495,tomato yellow leaf distortion deltasatellite 1,plants,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tolecusatellitidae,NaN,Deltasatellite,NaN,Deltasatellite solaniflavusprimi
16229,KU232893,KU232893,tomato yellow leaf distortion deltasatellite 2,plants,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tolecusatellitidae,NaN,Deltasatellite,NaN,Deltasatellite solaniflavussecundi
16230,AB522601,AB522601,Heterocapsa circularisquama DNA virus 01,protists,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Dinodnavirus,NaN,Heterocapsa circularisquama DNA virus 01

In [3]:
rawclassdf=pd.read_csv('../data/train/add_names.txt', sep='\t')
rawclassdf['#']= rawclassdf["#"].str.replace(r"\.\d+$", "", regex=True)
rawclassdf.rename(columns={'#':'contigId'}, inplace=True)
rawclassdf

,contigId,# contig,classification,reason,lineage,lineage scores (f: 0.5),superkingdom,phylum,class,order,family,genus,species
0,AB000906,AB000906.1_1,taxid assigned,based on 1/1 ORFs,1;10239;2559587;2732396;2732408;2732506;464095...,1.00;1.00;1.00;1.00;1.00;1.00;1.00;1.00;1.00;1...,Viruses: 1.00,Pisuviricota: 1.00,Pisoniviricetes: 1.00,Picornavirales: 1.00,Iflaviridae: 1.00,Iflavirus: 1.00,Iflavirus flacherie: 1.00
1,AB000920,AB000920.1_1,taxid assigned,based on 1/1 ORFs,1;10239;1458186;1441744;2169630;2845608;1455651*,1.00;1.00;1.00;1.00;1.00;1.00;1.00,Viruses: 1.00,NaN,NaN,NaN,Alphasatellitidae: 1.00,Mivedwarsatellite: 1.00,Milk vetch dwarf China alphasatellite: 1.00
2,AB000922,AB000922.1_1,taxid assigned,based on 1/1 ORFs,1;10239;1458186;1441744;2169627;2169834;1455654*,1.00;1.00;1.00;1.00;1.00;1.00;1.00,Viruses: 1.00,NaN,NaN,NaN,Alphasatellitidae: 1.00,Clostunsatellite: 1.00,Milk vetch dwarf alphasatellite 2: 1.00
3,AB000923,AB000923.1_1,taxid assigned,based on 1/1 ORFs,1;10239;2731342;2732092;2732416;2732423;273253...,1.00;1.00;1.00;1.00;1.00;1.00;1.00;1.00;1.00;1.00,Viruses: 1.00,Cressdnaviricota: 1.00,Arfiviricetes: 1.00,Mulpavirales: 1.00,Nanoviridae: 1.00,Nanovirus: 1.00,Milk vetch dwarf virus: 1.00
4,AB002632,AB002632.1_1,taxid assigned,based on 1/1 ORFs,1;10239;2731342;2732090;2732410;2732411;273209...,1.00;1.00;1.00;1.00;1.00;1.00;1.00;1.00;1.00,Viruses: 1.00,Hofneiviricota: 1.00,Faserviricetes: 1.00,Tubulavirales: 1.00,Inoviridae: 1.00,Saetivirus: 1.00,no support
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16067,Z48630,Z48630.1_1,no taxid assigned,no hits to database,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16068,Z69620,Z69620.1_1,taxid assigned,based on 1/1 ORFs,1;10239;2559587;2732396;2732408;2732506;464095...,1.00;1.00;1.00;1.00;1.00;1.00;1.00;1.00;1.00;1.00,Viruses: 1.00,Pisuviricota: 1.00,Pisoniviricetes: 1.00,Picornavirales: 1.00,Caliciviridae: 1.00,Lagovirus: 1.00,European brown hare syndrome virus: 1.00
16069,Z69910,Z69910.1_1,taxid assigned,based on 1/1 ORFs,1;10239;2559587;2732396;2732406;2732463;273254...,1.00;1.00;1.00;1.00;1.00;1.00;1.00;1.00;1.00;1...,Viruses: 1.00,Kitrinoviricota: 1.00,Tolucaviricetes: 1.00,Tolivirales: 1.00,Tombusviridae: 1.00,Umbravirus: 1.00,Umbravirus arachidis: 1.00
16070,Z73124,Z73124.1_1,taxid assigned,based on 1/1 ORFs,1;10239;2559587;2732396;2732408;2732507;273255...,1.00;1.00;1.00;1.00;1.00;1.00;1.00;1.00;1.00;1.00,Viruses: 1.00,Pisuviricota: 1.00,Stelpaviricetes: 1.00,Patatavirales: 1.00,Potyviridae: 1.00,Ipomovirus: 1.00,Sweet potato mild mottle virus: 1.00
16071,Z97873,Z97873.1_1,taxid assigned,based on 1/1 ORFs,1;10239;2559587;2732396;2732406;2732461;273254...,1.00;1.00;1.00;1.00;1.00;1.00;1.00;1.00;1.00;1.00,Viruses: 1.00,Kitrinoviricota: 1.00,Alsuviricetes: 1.00,Martellivirales: 1.00,Virgaviridae: 1.00,Pomovirus: 1.00,Beet soil-borne virus: 1.00

In [4]:
rscudf=pd.read_csv('../data/train/combine_RSCU.csv', sep=',')
rscudf['id']= rscudf["id"].str.replace(r"\.\d+$", "", regex=True)
rscudf.rename(columns={'id':'contigId'}, inplace=True)
rscudf

,contigId,TTT,TTC,TTA,TTG,CTT,CTC,CTA,CTG,ATT,...,CGG,AGA,AGG,GGT,GGC,GGA,GGG,TAA,TAG,TGA
0,AF013397,1.20,0.80,0.21,0.00,0.62,1.86,1.03,2.28,1.50,...,1.11,1.78,2.00,0.39,0.65,1.81,1.16,0,0,0
1,AC_000012,1.68,0.32,1.05,1.21,1.15,0.59,0.78,1.21,1.62,...,0.71,1.10,0.64,1.08,0.87,1.28,0.77,0,0,0
2,EF159731,2.00,0.00,0.00,1.50,2.25,2.25,0.00,0.00,2.44,...,0.86,1.29,1.29,1.67,0.67,1.00,0.67,0,0,0
3,EU938659,1.24,0.76,1.04,1.65,1.10,0.61,0.80,0.80,1.40,...,0.44,2.93,2.20,1.20,0.67,1.20,0.93,0,0,0
4,GQ303582,1.29,0.71,1.50,0.75,0.75,1.50,0.75,0.75,1.62,...,0.00,2.57,2.57,2.67,0.53,0.27,0.53,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16159,KY662287,1.00,1.00,1.20,1.20,2.40,0.80,0.00,0.40,1.00,...,0.00,3.33,2.67,2.00,0.80,0.40,0.80,0,0,0
16160,MG581962,1.25,0.75,0.41,1.86,1.86,1.24,0.62,0.00,1.64,...,1.20,0.60,0.90,0.76,0.38,1.71,1.14,0,0,0
16161,MH397359,1.27,0.73,0.81,1.62,1.30,1.14,0.32,0.81,1.50,...,0.60,2.10,1.50,1.07,0.27,1.60,1.07,0,0,0
16162,MN532677,1.12,0.88,0.71,1.41,1.50,0.88,0.62,0.88,1.00,...,0.86,1.20,1.29,1.38,0.87,0.73,1.02,0,0,0
16163,OP150929,1.33,0.67,0.00,0.00,2.18,3.27,0.00,0.55,3.00,...,2.40,0.00,2.40,0.80,2.40,0.00,0.80,0,0,0

In [5]:
tnfdf=pd.read_csv('../data/train/virus_final_tnf.csv', sep=',')
tnfdf['Contig']= tnfdf["Contig"].str.replace(r"\.\d+$", "", regex=True)
tnfdf.rename(columns={'Contig':'contigId'}, inplace=True)
tnfdf

,contigId,AAAA,AAAC,AAAG,AAAT,AACA,AACC,AACG,AACT,AAGA,...,TTCG,TTCT,TTGA,TTGC,TTGG,TTGT,TTTA,TTTC,TTTG,TTTT
0,CASDWV010005094,0.000402,0.000402,0.000909,-0.001372,0.000402,-0.000105,-0.000612,-0.000105,0.000655,...,0.001669,0.001416,0.001922,0.000402,0.003443,0.000148,-0.001625,0.003696,0.000655,-0.000865
1,CASDWV010005080,0.004429,0.001487,0.002958,0.001487,0.001242,-0.000229,0.000997,0.000997,0.000752,...,0.000507,-0.000719,0.000752,0.000507,0.003694,0.000016,0.004184,0.000997,0.000997,0.003694
2,CASDWV010005072,-0.000177,-0.001509,0.001155,0.001954,-0.000976,0.000089,0.000356,-0.000710,0.000889,...,0.002487,0.001155,0.002487,0.000356,0.001954,0.000089,0.002753,0.001155,0.001421,0.002753
3,CASDWV010005069,-0.001516,-0.001250,0.001671,-0.000719,-0.000719,-0.001250,-0.000985,-0.000188,0.003265,...,0.001140,0.004593,0.002203,0.000343,0.003265,0.001671,-0.000453,0.003265,0.002468,0.000875
4,CASDWV010005068,-0.000985,-0.001516,-0.000189,-0.002844,-0.000720,-0.000189,-0.000720,0.000077,0.000873,...,0.003529,0.002467,0.002467,0.001139,0.001935,-0.000985,-0.003110,0.002201,0.001670,0.001139
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16162,UPSH01000001,0.007537,0.003103,0.002915,0.001752,0.005997,-0.000785,-0.000175,0.002849,0.003449,...,-0.000757,0.002612,0.004110,-0.000968,-0.000593,0.004688,0.002367,0.001486,0.004133,0.007741
16163,CAJDKB010000002,0.006676,0.003864,0.003741,0.005393,0.005023,0.000139,-0.000255,0.002458,0.002359,...,-0.002846,0.003543,0.003371,0.000041,0.000805,0.004037,0.006898,0.003469,0.003864,0.009710
16164,CAJCJZ010000002,0.013144,0.002437,0.002249,0.012466,0.003630,-0.000852,-0.001378,0.002647,0.001418,...,-0.001449,0.006650,0.003150,0.000517,0.000002,0.004250,0.012314,0.009154,0.005023,0.024999
16165,CAJDJZ010000002,0.011100,0.003154,0.005805,0.006065,0.005095,0.000158,-0.000777,0.002388,0.006684,...,-0.002387,0.001874,0.001459,-0.000770,-0.000918,0.001283,0.006445,0.000088,0.000904,0.004673
16166,CAJDKA010000002,0.010142,0.004660,0.005276,0.005641,0.005661,0.000841,0.000118,0.002836,0.006237,...,-0.001871,0.002611,0.002193,-0.000346,-0.000472,0.001669,0.005322,0.000867,0.001384,0.004421

In [6]:
tnfdf_Contigs = set(tnfdf['contigId'])
rscudf_Contigs = set(rscudf['contigId'])
rawclassdf_Contigs = set(rawclassdf['contigId'])
classdf_Contigs = set(classdf['contigId'])

common_Contigs = tnfdf_Contigs & rscudf_Contigs & rawclassdf_Contigs & classdf_Contigs
print(len(common_Contigs))

16067

In [7]:
filtered_tnfdf = tnfdf[tnfdf['contigId'].isin(common_Contigs)]
filtered_rscudf = rscudf[rscudf['contigId'].isin(common_Contigs)]
filtered_rawclassdf = rawclassdf[rawclassdf['contigId'].isin(common_Contigs)]
filtered_classdf = classdf[classdf['contigId'].isin(common_Contigs)]

In [8]:
hcname=['phylum', 'class', 'order', 'family', 'genus', 'species']

In [9]:
raw_clas_dict = {}
raw_clas_score_dict={}
for index, row in filtered_rawclassdf.iterrows():
    base_id = row["contigId"]
    taxonomic_levels = []
    score_list = []
    for key in ['phylum', 'class', 'order', 'family', 'genus', 'species']:
        if pd.isna(row[key]):
            taxonomic_levels.append(None)
            score_list.append(0)
        else:
            if len(row[key].split(": ")) > 1:
                taxonomic_levels.append(row[key].split(": ")[0])
                score_list.append(float(row[key].split(": ")[1]))
            else:
                taxonomic_levels.append(None)
                score_list.append(0)
    raw_clas_dict[base_id] = taxonomic_levels
    raw_clas_score_dict[base_id] = score_list
print(len(raw_clas_dict))

16067

In [24]:
clas_dict = {}
for index, row in filtered_classdf.iterrows():
    base_id = row["contigId"]
    taxonomic_levels = []
    for key in ['Phylum', 'Class', 'Order', 'Family', 'Genus', 'Species']:
        if pd.isna(row[key]):
            taxonomic_levels.append(None)
        else:
            taxonomic_levels.append(row[key])
    clas_dict[base_id] = taxonomic_levels
print(len(clas_dict))
#clas_dict

16067

In [ ]:
#pip install gensim
from gensim.models import Word2Vec
node_names = list(clas_dict.values())+list(raw_clas_dict.values())
word2vec_model = Word2Vec(sentences=node_names, vector_size=16, window=3, min_count=1, workers=4)
word2vec_model.save("word2vec.model")

In [34]:
clas_df = pd.DataFrame.from_dict(clas_dict, orient='index', columns=hcname)
clas_df.index.name = 'contigId'
raw_classdf = pd.DataFrame.from_dict(raw_clas_dict, orient='index', columns=hcname)
raw_classdf.index.name = 'contigId'
raw_classdf

,phylum,class,order,family,genus,species
contigId,,,,,,
AB000906,Pisuviricota,Pisoniviricetes,Picornavirales,Iflaviridae,Iflavirus,Iflavirus flacherie
AB000920,None,None,None,Alphasatellitidae,Mivedwarsatellite,Milk vetch dwarf China alphasatellite
AB000922,None,None,None,Alphasatellitidae,Clostunsatellite,Milk vetch dwarf alphasatellite 2
AB000923,Cressdnaviricota,Arfiviricetes,Mulpavirales,Nanoviridae,Nanovirus,Milk vetch dwarf virus
AB002632,Hofneiviricota,Faserviricetes,Tubulavirales,Inoviridae,Saetivirus,None
...,...,...,...,...,...,...
Z48630,None,None,None,None,None,None
Z69620,Pisuviricota,Pisoniviricetes,Picornavirales,Caliciviridae,Lagovirus,European brown hare syndrome virus
Z69910,Kitrinoviricota,Tolucaviricetes,Tolivirales,Tombusviridae,Umbravirus,Umbravirus arachidis
Z73124,Pisuviricota,Stelpaviricetes,Patatavirales,Potyviridae,Ipomovirus,Sweet potato mild mottle virus
Z97873,Kitrinoviricota,Alsuviricetes,Martellivirales,Virgaviridae,Pomovirus,Beet soil-borne virus

In [35]:
clas_df

,phylum,class,order,family,genus,species
contigId,,,,,,
MH447526,Taleaviricota,Tokiviricetes,Ligamenvirales,Lipothrixviridae,Alphalipothrixvirus,Alphalipothrixvirus beppuense
MK064563,Taleaviricota,Tokiviricetes,Ligamenvirales,Lipothrixviridae,Alphalipothrixvirus,Alphalipothrixvirus umijigokuense
AM087120,Taleaviricota,Tokiviricetes,Ligamenvirales,Lipothrixviridae,Betalipothrixvirus,Betalipothrixvirus acidiani
AF440571,Taleaviricota,Tokiviricetes,Ligamenvirales,Lipothrixviridae,Betalipothrixvirus,Betalipothrixvirus hveragerdiense
AM087122,Taleaviricota,Tokiviricetes,Ligamenvirales,Lipothrixviridae,Betalipothrixvirus,Betalipothrixvirus pezzuloense
...,...,...,...,...,...,...
FN435836,None,None,None,Tolecusatellitidae,Betasatellite,Betasatellite verrnoniaflavi
JF733779,None,None,None,Tolecusatellitidae,Betasatellite,Betasatellite verrnoniaflavusfujianense
JX443646,None,None,None,Tolecusatellitidae,Betasatellite,Betasatellite vignae
AJ542499,None,None,None,Tolecusatellitidae,Betasatellite,Betasatellite zinniae
AB522601,None,None,None,None,Dinodnavirus,Heterocapsa circularisquama DNA virus 01

In [36]:
#raw_classdf+clas_df
combined_df = pd.concat([raw_classdf, clas_df], axis=0)
combined_df

,phylum,class,order,family,genus,species
contigId,,,,,,
AB000906,Pisuviricota,Pisoniviricetes,Picornavirales,Iflaviridae,Iflavirus,Iflavirus flacherie
AB000920,None,None,None,Alphasatellitidae,Mivedwarsatellite,Milk vetch dwarf China alphasatellite
AB000922,None,None,None,Alphasatellitidae,Clostunsatellite,Milk vetch dwarf alphasatellite 2
AB000923,Cressdnaviricota,Arfiviricetes,Mulpavirales,Nanoviridae,Nanovirus,Milk vetch dwarf virus
AB002632,Hofneiviricota,Faserviricetes,Tubulavirales,Inoviridae,Saetivirus,None
...,...,...,...,...,...,...
FN435836,None,None,None,Tolecusatellitidae,Betasatellite,Betasatellite verrnoniaflavi
JF733779,None,None,None,Tolecusatellitidae,Betasatellite,Betasatellite verrnoniaflavusfujianense
JX443646,None,None,None,Tolecusatellitidae,Betasatellite,Betasatellite vignae
AJ542499,None,None,None,Tolecusatellitidae,Betasatellite,Betasatellite zinniae
AB522601,None,None,None,None,Dinodnavirus,Heterocapsa circularisquama DNA virus 01

In [37]:
from sklearn.preprocessing import LabelEncoder
import pickle
label_columns = ['phylum', 'class', 'order', 'family', 'genus', 'species']
encoders = {}  # 用于存储训练好的编码器，以便将来可以反向转换或者新增数据时再对其进行 transform

for col in label_columns:
    le = LabelEncoder()
    combined_df[col] = le.fit_transform(combined_df[col])
    encoders[col] = le

with open('encoders.pkl', 'wb') as f:
    pickle.dump(encoders, f)

In [ ]:
for col in label_columns:
    clas_df[col] = encoders[col].transform(clas_df[col])
clas_df

          phylum  class  order  family  genus  species
contigId
MH447526      16     39     38     159     93      481
MK064563      16     39     38     159     93      482
AM087120      16     39     38     159    413     2251
AF440571      16     39     38     159    413     2252
AM087122      16     39     38     159    413     2253
...          ...    ...    ...     ...    ...      ...
FN435836      18     43     86     304    427     2492
JF733779      18     43     86     304    427     2493
JX443646      18     43     86     304    427     2494
AJ542499      18     43     86     304    427     2495
AB522601      18     43     86     334    962     7247

[16067 rows x 6 columns]

In [32]:
for col in label_columns:
    raw_classdf[col] = encoders[col].transform(raw_classdf[col])
raw_classdf

          phylum  class  order  family  genus  species
contigId
AB000906      13     29     60     139   1554     8118
AB000920      18     43     86      15   2132    10318
AB000922      18     43     86      15    785    10319
AB000923       3      3     46     196   2235    10320
AB002632       6     11     80     140   2842    17671
...          ...    ...    ...     ...    ...      ...
Z48630        18     43     86     334   3691    17671
Z69620        13     29     60      62   1813     5648
Z69910         7     40     79     305   3400    16434
Z73124        13     36     56     250   1597    15365
Z97873         7      1     40     322   2630     1577

[16067 rows x 6 columns]

In [94]:
#filtered_tnfdf/filtered_rscudf/filtered_rawclassdf/filtered_classdf
traindata = pd.merge(filtered_tnfdf, filtered_rscudf, on='contigId')
traindata = pd.merge(traindata, raw_classdf, on='contigId')
traindata = pd.merge(traindata, clas_df, on='contigId')
traindata

,contigId,AAAA,AAAC,AAAG,AAAT,AACA,AACC,AACG,AACT,AAGA,...,order_x,family_x,genus_x,species_x,phylum_y,class_y,order_y,family_y,genus_y,species_y
0,CASDWV010005094,0.000402,0.000402,0.000909,-0.001372,0.000402,-0.000105,-0.000612,-0.000105,0.000655,...,78,295,3691,17671,8,18,78,295,1482,7483
1,CASDWV010005080,0.004429,0.001487,0.002958,0.001487,0.001242,-0.000229,0.000997,0.000997,0.000752,...,86,334,3691,17671,8,18,52,41,595,3130
2,CASDWV010005072,-0.000177,-0.001509,0.001155,0.001954,-0.000976,0.000089,0.000356,-0.000710,0.000889,...,78,295,2939,14465,8,18,78,295,704,3690
3,CASDWV010005069,-0.001516,-0.001250,0.001671,-0.000719,-0.000719,-0.001250,-0.000985,-0.000188,0.003265,...,52,286,1586,8253,8,18,52,286,3501,16976
4,CASDWV010005068,-0.000985,-0.001516,-0.000189,-0.002844,-0.000720,-0.000189,-0.000720,0.000077,0.000873,...,78,295,3691,17671,8,18,78,295,1482,7427
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16062,UPSH01000001,0.007537,0.003103,0.002915,0.001752,0.005997,-0.000785,-0.000175,0.002849,0.003449,...,86,334,3691,17671,10,22,28,183,3629,17498
16063,CAJDKB010000002,0.006676,0.003864,0.003741,0.005393,0.005023,0.000139,-0.000255,0.002458,0.002359,...,86,334,3691,17671,17,5,86,334,904,4718
16064,CAJCJZ010000002,0.013144,0.002437,0.002249,0.012466,0.003630,-0.000852,-0.001378,0.002647,0.001418,...,86,334,3478,17671,17,5,86,334,3478,16877
16065,CAJDJZ010000002,0.011100,0.003154,0.005805,0.006065,0.005095,0.000158,-0.000777,0.002388,0.006684,...,86,136,1749,17671,17,5,86,136,1749,8798
16066,CAJDKA010000002,0.010142,0.004660,0.005276,0.005641,0.005661,0.000841,0.000118,0.002836,0.006237,...,86,136,2915,17671,17,5,86,136,2915,14337

In [99]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder, MinMaxScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.decomposition import PCA
from category_encoders import TargetEncoder

# 假设 x_features 是一个已经存在的 DataFrame
scaler = StandardScaler()
minmax_scaler = MinMaxScaler()

# 定义特征的列索引
feature1_cols = traindata.columns[1:65]  # 数值特征1
feature2_cols = traindata.columns[65:321]  # 数值特征2
feature3_cols =  traindata.columns[322:327]  # 分类特征

# 创建列转换器
preprocessor = ColumnTransformer(
    transformers=[
        ('f1', scaler, feature1_cols),
        ('f2', minmax_scaler, feature2_cols),
        ('f3', scaler, feature3_cols)  # 放大分类特征
    ])

pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
])

# 应用预处理
x_features = pipeline.fit_transform(traindata)

x_features

array([[-0.52269083, -0.22415945, -0.33585399, ...,  0.69791514,
         1.19434575,  0.81851722],
       [ 0.12289801,  0.23949905,  0.36805204, ...,  1.05240722,
         1.19434575,  0.81851722],
       [-0.61547699, -1.04043621, -0.2512704 , ...,  0.69791514,
         0.59526365,  0.25281025],
       ...,
       [ 1.52002204,  0.64506514,  0.12458575, ...,  1.05240722,
         1.02465893,  0.81851722],
       [ 1.19234002,  0.9515723 ,  1.34588799, ..., -0.7473218 ,
        -0.3527519 ,  0.81851722],
       [ 1.03877276,  1.59472997,  1.1641744 , ..., -0.7473218 ,
         0.57614401,  0.81851722]], shape=(16067, 325))

In [111]:
y_label=traindata[traindata.columns[327:333]].to_numpy()

In [112]:
import pickle
with open('datax', 'wb') as f:
    pickle.dump(x_features, f)
with open('datay', 'wb') as f:
    pickle.dump(y_label, f)